### ISSUE TITLE
Remove codepaths and features that are not used in the build service

### ISSUE THREAD

**Issue by chee** [chee/obt5fork#7]
The build service uses obt 3 times!

[obt.demo](https://github.com/Financial-Times/origami-build-service/blob/3770a76ca3df19abaf99936110e171370b41bce5/lib/democompiler.js#L61)
[obt.build.js](https://github.com/Financial-Times/origami-build-service/blob/3770a76ca3df19abaf99936110e171370b41bce5/lib/jsbundler.js#L149)
[obt.build.sass](https://github.com/Financial-Times/origami-build-service/blob/3770a76ca3df19abaf99936110e171370b41bce5/lib/cssbundler.js#L131)

Let's remove anything that it doesn't need!

## Removed
- [x] [Command line interface](https://github.com/Financial-Times/obt5fork/pull/2)!
- [x] [Demo server](https://github.com/Financial-Times/obt5fork/pull/6)!
- [x] `demoConfig.dist == false`
- [x] Verify task
- [x] Install task
- [x] Test task

**Comment by chee** [comment]
will look through the config object of each of these and see if there are any more entirely unused paths:)

https://github.com/Financial-Times/origami-build-service/blob/3770a76ca3df19abaf99936110e171370b41bce5/lib/jsbundler.js#L137-L147

**Comment by chee** [comment]
okay, so it looks like `demoConfig.dist` is always `true` so i'll work on removing the non-dist path from demo, and make a PR

**Comment by chee** [comment]
https://github.com/Financial-Times/obt5fork/pull/10 for removing those tasks

**Comment by chee** [comment]
we could also remove `if (src)` in js and sass builds, because we know they will always be there. but there isn't much code for that, and there is no `else`.

it might allow us to remove some files helpers, though, and then remove their dependencies

**Comment by JakeChampion** [comment]
This looks to be completed via https://github.com/Financial-Times/obt5fork/pull/10, I'll close the issue for now.
